sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kMYDG8xghJnkl/F2MxW0I/+AEB+ih/Zc6pLNTEfzBJh1Zyac47LomEXLf3Y6+WKvM4NViIDwfJ3J6U7U/TEAIzui4SnL7NnVdlYWuKBcoiYeAIlU0MCjaC+Y8lek2Ngst4m+r5OhwcCQzgH3gduhy3226OtR0autuqXKchSjGrNSuVQ3yVMj6BvUKYgVLVZQqjXwrXp5N6uzk/AuqilH3/TUsLTIDSUGd5QxGOFLNC4N83GbCbACn2VCdqzf1r2N8dDkroFuGiChZWXnpIJH9hXSGbrRtI5qnbW2QNDW98VldTtK8z5WeWmtOu28esTJ5OAQ9xZfzDF7TXMxO0XprK8VJfrcCYFUViVjZlk9WoW/cxNXYgxiLu7+aP9cQMAWLGV4v6p85/RcnHBFQWZb4lnv22kqTFneocMg87vwd4OtQwD4CJny26EwWZew/81zyVPujrDxGrmUJQLts77rWF3feMC8bNlv+VHUK9Pdtb1M2ERT+IQSK7idv1jzCM3JwccmXnaKhkzdGUId0lZQTgG52HRvlnJjbqotr3Uvp6iRsRF7njv1FGBBdlex34n4Ol7f58Qol+mvrgOceXw4eMvFg229vAlDNyUADXqdr6UBwoF3kIAFpiO3faR9ZcUWE6AieITWuJDhdBGWgHfMhKy/uDTHaMXENU4d7Pp5b2c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Orthodoxy_130
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy